service: serverless-practice
provider:
  name: aws
  runtime: nodejs10.x
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
  upload:
    handler: handler.upload
    events:
      - http:
          path: /upload
          method: get